### PR TITLE
added pull request template

### PR DESCRIPTION
**Pull request by MitchellBerend**
I thought it would be nice to have a pr template so I took inspiration from the kubernetes one. This aims to have a more consistent process for prs moving forward.

### CODE REVIEW

**Comment by chshersh** [comment]
@MitchellBerend This is a great idea 👏🏻 

My only feedback would be to simplify the template as `tool-sync` is not as complicated a project as K8S 😅 `tool-sync` also has a much smaller user base. So we can grow the number of contributors by lowering contributing requirements at this stage. In my vision, long PR templates can be off-putting when all people want is to add a patch.

A few remarks:

1. I don't think we need to mention `CONTRIBUTING.md` and we can rely on GitHub UI here that warns about reading `CONTRIBUTING.md`. It's also my general expectation that people read the contributing guide before contributing to the project.
2. The `/kind` commands can be removed. We don't have the tooling to automatically set labels based on this and we can set them manually after PR is open.
3. External contributors can't set the labels on their own.

Based on these remarks, I propose the following template:

```markdown
<--! PR title template: [#ISSUE_NUMBER] <short description>
     Example:           [#42] Solve problem X
-->

Resolves #PUT_ISSUE_NUMBER_HERE_IF_APPLICABLE

Write description of your changes here

### Additional tasks

- [ ] Documentation for changes provided/changed
- [ ] Tests added
```

**Comment by MitchellBerend** [comment]
> long PR templates can be off-putting when all people want is to add a patch.

I can definitely understand that a long doc can be off putting for others even though I like longer docs.
I will add your template since I think we should have some template so there is some amount of similar structure in prs.

**Comment by MitchellBerend** [comment]
Is there a way to skip ci for changes like this? I don't think it makes sense to waste resources when a template or `README.md` gets changed since we don't have doc tests (yet).

**Review by chshersh — APPROVED** [review]

**Comment by chshersh** [comment]
@MitchellBerend You can add `[skip ci]` to the commit message and CI won't run for this commit. It can be handy for documentation-only changes

* https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/

**Pull request merged**
