### PR TITLE
[#116] prevent sha from being included in asset name hits

### LINKED ISSUE #116: Can't sync starship
https://github.com/starship/starship/releases

```toml
[starship] 
owner = "starship"
repo = "starship"
exe_name = "starship"
asset_name.windows = "starship-x86_64-pc-windows-msvc.zip"
```

```sh
>tool sync
x  starship
Multiple name matches found for this asset:

         * starship-x86_64-pc-windows-msvc.zip
         * starship-x86_64-pc-windows-msvc.zip.sha256

Please add one of these to the config.
```

### PR DESCRIPTION
**Pull request by MitchellBerend**
Resolves #116 
This pr adds filters out the `sha` substring in the asset name so it does not get trigger a `MultipleFound` error. It also augments a test to check this behaviour.

Thanks to @slyshykO for finding this bug and reporting it.

### Additional tasks

- [ ] Documentation for changes provided/changed
- [x] Tests added

### CODE REVIEW

**Comment by MitchellBerend** [comment]
Maybe its better to target a specific region in the asset name? Something like after the last instance of `.` so for example `shadow.tar.gz` still gets recognized as a hit.

**Comment by slyshykO** [comment]
I propose to add a filter to settings and use a wildcard for filtering

**Comment by MitchellBerend** [comment]
Do you have suggestions on what this would look like?

**Comment by slyshykO** [comment]
> Do you have suggestions on what this would look like?

```toml
[starship] 
owner = "starship"
repo = "starship"
exe_name = "starship"
asset_name.windows = "starship-x86_64-pc-windows-msvc.zip"

asset_name.exclude = ["*.tar.gz", "*.sha256"]
```

**Comment by slyshykO** [comment]
@MitchellBerend can I add a new dependency https://crates.io/crates/wildmatch?

**Comment by chshersh** [comment]
Hey, @MitchellBerend @slyshykO, could I ask you not to rush the implementation of this? I would like everyone to agree on the final design before we spent a lot of time implementing code that will be thrown away 🙏🏻 

I'll try to provide my thoughts in #50 and I'll mention everyone to request feedback 🙂 

<hr>

As for `wildmatch`: do you mean to use it to implement a separate `asset_name.exclude` field? I'm not sure I want to go that way. And `wildmatch` doesn't support `$` so we can solve this problem without a separate field.

I'd rather spend some time thinking about proper filtering (inclusion/exclusion) mechanism 🤔

**Comment by slyshykO** [comment]
> As for wildmatch: do you mean to use it to implement a separate asset_name.exclude field? I'm not sure I want to go that way.

As an alternative, there is possible to consider an asset's names as wildcards.
As an example: `*x86_64-pc-windows-msvc.zip` .

**Comment by MitchellBerend** [comment]
I'm closing this pr so others won't see a pr linked to the original issue.

**Pull request closed without merging**
